### ISSUE TITLE
Handling extra yaml fields

### ISSUE THREAD

**Issue by Sparrow0hawk** [coderefinery/git-calendar#8]
Thanks for this super project!

I'm looking at building a [jekyll website](https://github.com/Sparrow0hawk/git-calendar-test) that builds off this calendar tool to render a simple website that shows events and offers the downloadable .ics file. I do this by creating markdown posts with yaml frontmatter extracted from the data yaml that is used by this git-calendar tool. I would like to add some additional yaml fields to handle things like event_urls explicitly within the jekyll site but found this isn't compatible with this tool.

Would there be a way of permissively allowing extra yaml tags that aren't used when building the .ics files?

**Comment by Sparrow0hawk** [comment]
You can test this on the [add-event-url branch](https://github.com/Sparrow0hawk/git-calendar-test/tree/add-event-url ) of my repo and just try and run the build.sh file.

It gives the following error:

```
./build.sh 
processing _data/example.yaml
processing _data/main.yaml
Traceback (most recent call last):
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/bin/git-calendar", line 8, in <module>
    sys.exit(main())
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/lib/python3.9/site-packages/git_calendar/build.py", line 55, in main
    calendar = yaml2ics.files_to_calendar([f])
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/lib/python3.9/site-packages/yaml2ics.py", line 180, in files_to_calendar
    all_events, name = files_to_events(files)
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/lib/python3.9/site-packages/yaml2ics.py", line 169, in files_to_events
    all_events.append(event_from_yaml(event, tz=tz))
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/lib/python3.9/site-packages/yaml2ics.py", line 68, in event_from_yaml
    event = ics.Event(**d)
  File "/Users/alexcoleman/projects/github/oss/socrse/git-calendar-test/venv/lib/python3.9/site-packages/ics/event.py", line 317, in __init__
    super().__init__(kwargs.pop("timespan"), summary, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'event_url'
```
